# Main evaluation config (MainEvaluation.py)
models_directory: defense-models # Directory that contains all the defense models that are going to be benchmarked
output_file: results/text-visualization.json # json file where the evaluation results will be saved

# One config section per defense model file in models_directory (file stem must match)
defense_model_train_configs:
  MyModel-v1:
    data:
      target_topologies: null
      train_pkl_path: data/train-gpt-oss-300.pkl
    validation_split: 0.2
    validation_seed: 368925297
    kmeans_config:
      random_state: 508978378
      threshold: 0.75
      max_k: 5
      n_components: 30
      n_neighbors: 25
      min_dist: 0.25
      umap_metric: cosine
    d_model: 384
    intraNode_layers: 6
    intraNode_heads: 8
    interNode_layers: 3
    interNode_heads: 8
    device: cuda
    learning_rate: 0.0001
    weight_decay: 0.0001
    scheduler:
      factor: 0.5
      patience: 5
      threshold: 1.0e-05
    batch_size: 16
    temperature: 0.15
    cohesion_weight: 0.5
    neighbor_weight: 0.35
    graph_separation_weight: 0.05
    loss_temperature: 0.3
    huber_delta: 1
    epochs: 100
    early_stop: 15
    improve_threshold: 0.001
    run_name: text-visualization
    model_name: text-viz
    save_path: best_model.pt

  

live_evaluation_config:
  timeout: 60 # Added a default value
  prompts_file: prompts/prompts_blindguard.json # Added a path

  # Question loader
  questions_path: DatasetManager.py
  questions_dataset_tag: MMLUPRO
  questions_random_seed: 28324

  # Debate + attacker settings
  num_agents: 8
  num_malicious_agents: 2
  malicious_seed: 12
  max_rounds: 3
  consensus_threshold: 1.0
  no_consensus_check: false 
  check_consensus_only_unflagged: true

  # Defense settings
  no_defense_baseline: false

  # Concurrency
  max_concurrent_inference: 300 # Added a default value

  # Questions
  num_questions: 0 
  new_random_each_question: true 
  n_questions_on_random_topo: 15
  topologies_seed: 213313
  density_range_for_random_topo: [0.6, 0.9]

  # Text processor
  text_processor_path: TextProcessingManager.py 
  text_processor_class_name: WindowsAndText 

  # Debug artifacts
  save_traces: false 
  clean_debates_with_empty_responses: true